export enum Privilege {
  MODERATOR     = 'PRIVILEGE_MODERATOR',
  ASSISTANT     = 'PRIVILEGE_ASSISTANT',
  JOURNALIST    = 'PRIVILEGE_JOURNALIST',
  INVESTIGATOR  = 'PRIVILEGE_INVESTIGATOR',
  AUTHORITY     = 'PRIVILEGE_AUTHORITY',
}
